### ISSUE TITLE
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by souza-gsdev** [Rocketseat/unform#195] opened 2020-03-03 12:56 UTC
Estou recebendo o erro: Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Quando uso a validação no form de acordo com a documentação.

```js
export default function AddProduct() {
  const formRef = useRef(null);

  async function handleSubmit(data) {
    try {
      formRef.current.setErrors({});

      const schema = Yup.object().shape({
        name: Yup.string().required('O nome do é obrigatório'),
        description: Yup.string().required('A descrição é obrigatória'),
        price: Yup.number()
          .typeError('Preço obrigatório')
          .required('O preço é obrigatório')
          .positive(),
        code: Yup.string().required('O código é obrigatório'),
        img_id: Yup.mixed().required('A imagem é obrigatória'),
      });

      await schema.validate(data, {
        abortEarly: false,
      });

      console.tron.log(data);

      if (data.file === undefined) {
        document.getElementById('error-file').innerHTML =
          'A imagem é obrigatória';
      }

      console.tron.log(data);
    } catch (err) {
      const validationErrors = {};

      if (err instanceof Yup.ValidationError) {
        console.tron.log(err);
        err.inner.forEach(error => {
          validationErrors[error.path] = error.message;
        });

        formRef.current.setErrors(validationErrors);
      }
    }
  }
  return (
    <ContainerProduct>
      <h1>Adicione Novo Produto</h1>
      <Form ref={formRef} onSubmit={handleSubmit}>
        <div>
          <ImgInput name="img_id" />
          <span id="error-file" />
        </div>
        <div>
          <Input name="name" placeholder="Nome" />
          <Textarea rows="10" name="description" placeholder="Descrição" />
          <Input type="number" name="price" placeholder="Preço" />
          <Input name="code" placeholder="Código" />
          <button type="submit">Enviar</button>
        </div>
      </Form>
    </ContainerProduct>
  );
}
```

**Comment by diego3g** [comment] 2020-03-11 16:16
Hello @souza-gsdev, i cannot reproduce the problem here.

Can you provide a Code Sandbox with the same code with the error?

Also, keep in mind to use english as primary language inside this repository :)

**Comment by rafaelbpa** [comment] 2020-03-11 19:48
I was with the same warning here.

Fixed exporting my input component with forwardRef (as the warning message suggest)
```
import React, { forwardRef } from 'react';
...
export default forwardRef(Input);
```

**Comment by diego3g** [comment] 2020-03-19 11:51
Closing this since there are no updates from the author.

Feel free to reopen the issue if the problem persists.

**Closed by diego3g** 2020-03-19 11:51 UTC
Labels: bug

**Comment by lucascco** [comment] 2020-04-02 01:30
Hi guys, I had the same problem of @souza-gsdev . 

Hi @diego3g, your student from RocketSeat here, rsrs 

In this case I was using only @rocketseat/unform and get de Form from this lib. Looking at   https://codesandbox.io/embed/agitated-tdd-uf177?autoresize=1&expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark
I see that the Form coming from @unform/web to use useRef.

To try fix this error in React, I installed @unform/web and @unform/core, so I get the Form from @unform/web instead of @rocketseat/unform. The useRef working but Unfortunately the initialData stop working.

Conclusion:
The component Form coming from @unform/web you can use useRef, and the same component imported from @rocketseat/unform, you can not use this useRef. Maybe that Form is not exposed to use in useRef.

Is there some way to solve this @diego3g ?

**Comment by Thixz** [comment] 2022-07-22 19:01
Hello, everyone!

I was facing the same problem here while using React Native.

The thing is you cant pass ref for a custom functional exported component by yourself like you pass when you're using a regular component like TextInput.

You'll have to pass this ref forward inside your function and then pass this ref for your component INSIDE your function.

REMEMBER TO IMPORT forwardRef from react

Something like this:

(CUSTOM INPUT COMPONENT THAT I'LL EXPORT TO REUSE)

export const StyledInput = React.forwardRef<(here you write the type of the component that'll receive ref),(here you put the props that your component will receive, in my case 'im using an interface to declare all props)>((props,ref) => {
return(

)
})

then you just import it in you main page and pass useRef hook normally.

My entire code :

import React,{ forwardRef } from "react";
import { Fumi } from "react-native-textinput-effects";

interface StyledTextInputProps {
placeholder: string;
icon: string;
isPassword: boolean;
onChangeText: (text: string) => void;
value?: string;
autoFocus?: boolean;
onFocus?: boolean;
onEndEditing?: () => void;
}

export const StyledInput = forwardRef<Fumi,StyledTextInputProps>((props,ref) => {
return(

)
})

const passwordInput = useRef(null);
<StyledInput
value={user}
placeholder="Usuário"
icon="user"
onChangeText={handleUserTextChange}
autoFocus={true}
isPassword={false}
onEndEditing={() => {
if (passwordInput && passwordInput.current) {
passwordInput.current.focus();
}
}}
/>
